# =============================================================================
# MongoDB — TESTING override values
# =============================================================================
global:
  defaultStorageClass: local-path

image:
  tag: "8.0"

architecture: standalone
auth:
  enabled: true
  existingSecret: mongodb-credentials
  existingSecretPasswordKey: mongodb-root-password

nodeSelector:
  kubernetes.io/hostname: master.local
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
persistence:
  enabled: true
  size: 2Gi
service:
  type: NodePort
  nodePorts:
    mongodb: "32017"
resources:
  requests:
    memory: 64Mi
    cpu: 50m
  limits:
    memory: 256Mi
    cpu: 250m
