# =============================================================================
# Kafka (bitnami) — STAGING override values
# =============================================================================
image:
  tag: "4.0"
controller:
  replicaCount: 1
  persistence:
    enabled: true
    size: 5Gi
    storageClass: local-path
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: "1"
broker:
  replicaCount: 0
listeners:
  client:
    protocol: SASL_PLAINTEXT
    name: CLIENT
    containerPort: 9092
sasl:
  enabledMechanisms: PLAIN
  interBrokerMechanism: PLAIN
  client:
    users: [kafka-user]
    existingSecret: kafka-credentials
    existingSecretPasswordKey: kafka-password
externalAccess:
  enabled: false
extraConfig: |
  offsets.topic.replication.factor=1
  default.replication.factor=1
  min.insync.replicas=1
kraft:
  enabled: true
zookeeper:
  enabled: false
