apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-kafka
  namespace: argocd
  finalizers: [resources-finalizer.argocd.io]
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: platform
  source:
    repoURL: https://github.com/johnmillermca/stardatadblabs
    targetRevision: HEAD
    path: manifests/strimzi
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      jsonPointers:
        - /metadata
        - /spec
        - /status
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRoleBinding
      name: strimzi-prod-strimzi-kafka-kafka-init
      jsonPointers:
        - /metadata
        - /subjects
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
