# ArgoCD Application – OpenBao
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openbao
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  sources:
    - repoURL: https://openbao.github.io/openbao-helm
      chart: openbao
      targetRevision: "0.28.5"
      helm:
        releaseName: openbao
        valueFiles:
          - $values/helm/openbao/values.yaml
    - repoURL: https://github.com/johnmillermca/stardatadblabs
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
