apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-operator
  namespace: argocd
  finalizers: [resources-finalizer.argocd.io]
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: platform
  sources:
    - repoURL: https://strimzi.io/charts/
      chart: strimzi-kafka-operator
      targetRevision: "1.1.0"
      helm:
        valueFiles:
          - $values/k8s-platform/helm/strimzi-operator/values.yaml
    - repoURL: https://github.com/johnmillermca/stardatadblabs
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: strimzi-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
