spark.master                             spark://spark-master-svc.prod.svc.cluster.local:7077
spark.sql.extensions                     org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.polaris                org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.polaris.type           rest
spark.sql.catalog.polaris.uri            http://polaris-rest.prod.svc.cluster.local:8181/api/catalog
spark.jars                               /usr/local/spark/conf/../../../lib/python3.11/site-packages/pyspark/jars/iceberg-spark-runtime.jar
spark.driver.extraClassPath              /usr/local/spark/conf/../../../lib/python3.11/site-packages/pyspark/jars/postgresql.jar
spark.executor.extraClassPath            /usr/local/spark/conf/../../../lib/python3.11/site-packages/pyspark/jars/postgresql.jar
