-- ============================================================
-- Pipeline DB — Migration 001 (runs against the `pipeline` database)
--
-- This migration is intentionally separate from the rbac DB
-- migrations.  Connect to the dedicated `pipeline` database:
--
--   psql -U pipeline -d pipeline -f 007_pipeline_db_schema.sql
--
-- Why a separate database?
-- ------------------------
-- The `pipeline` DB is the authoritative cross-service CDC
-- sync-point store.  It is read by:
--   • The Spark bulk-copy job  (writes watermarks after each table)
--   • The Debezium bootstrap script (resolves Oracle SCN before registering
--     the connector — no Spark session needed)
--   • Monitoring / alerting tooling (plain psql)
--
-- Keeping it separate from `rbac` avoids schema coupling and
-- allows independent backup / restore cadences.
--
-- Tables
-- ------
-- pipeline_watermarks  — one row per (source_db, source_schema, table_name)
--                        upserted after every successful bulk-copy run.
--                        Contains the Snowflake sf_extraction_ts that maps
--                        to an Oracle SCN via TIMESTAMP_TO_SCN().
--
-- pipeline_run_log     — one row per full pipeline run, for audit/monitoring.
-- ============================================================

-- ── pipeline_watermarks ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS pipeline_watermarks (
    id               BIGSERIAL    PRIMARY KEY,

    -- Source identification (upsert key)
    source_db        TEXT         NOT NULL,          -- e.g. SNOWFLAKE_SAMPLE_DATA
    source_schema    TEXT         NOT NULL,          -- e.g. TPCDS_SF10TCL
    table_name       TEXT         NOT NULL,          -- lower-cased, e.g. income_band

    -- Sync-point: Snowflake server-side CURRENT_TIMESTAMP() captured
    -- immediately before the first batch SELECT for this table.
    -- The Debezium bootstrap script converts this to an Oracle SCN via
    --   SELECT TIMESTAMP_TO_SCN(TO_TIMESTAMP_TZ(...)) FROM DUAL
    sf_extraction_ts TEXT         NOT NULL,          -- ISO-8601 UTC e.g. "2026-08-18T04:01:39.123456Z"

    -- Oracle SCN resolved by Debezium bootstrap script
    -- NULL until bootstrap has queried Oracle.
    oracle_start_scn BIGINT       DEFAULT NULL,

    -- Copy statistics
    rows_copied      BIGINT       NOT NULL DEFAULT 0,
    pipeline_run_ts  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    -- Target Iceberg namespace (== lower(source_schema))
    iceberg_namespace TEXT        NOT NULL,

    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    UNIQUE (source_db, source_schema, table_name)
);

CREATE OR REPLACE FUNCTION _set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$;

DROP TRIGGER IF EXISTS trg_pw_updated_at ON pipeline_watermarks;
CREATE TRIGGER trg_pw_updated_at
    BEFORE UPDATE ON pipeline_watermarks
    FOR EACH ROW EXECUTE FUNCTION _set_updated_at();

CREATE INDEX IF NOT EXISTS idx_pw_source
    ON pipeline_watermarks (source_db, source_schema, table_name);

GRANT ALL PRIVILEGES ON TABLE pipeline_watermarks TO pipeline;
GRANT USAGE, SELECT ON SEQUENCE pipeline_watermarks_id_seq TO pipeline;


-- ── pipeline_run_log ───────────────────────────────────────────────────────────
-- One row per full Snowflake → Iceberg pipeline run, for audit and monitoring.
CREATE TABLE IF NOT EXISTS pipeline_run_log (
    id              BIGSERIAL    PRIMARY KEY,
    run_id          TEXT         NOT NULL UNIQUE,   -- UUID generated by Spark driver
    source_db       TEXT         NOT NULL,
    source_schema   TEXT         NOT NULL,
    started_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    finished_at     TIMESTAMPTZ  DEFAULT NULL,
    tables_ok       INT          NOT NULL DEFAULT 0,
    tables_failed   INT          NOT NULL DEFAULT 0,
    tables_skipped  INT          NOT NULL DEFAULT 0,
    total_rows      BIGINT       NOT NULL DEFAULT 0,
    status          TEXT         NOT NULL DEFAULT 'running',  -- running|success|partial|failed
    error_detail    TEXT         DEFAULT NULL
);

GRANT ALL PRIVILEGES ON TABLE pipeline_run_log TO pipeline;
GRANT USAGE, SELECT ON SEQUENCE pipeline_run_log_id_seq TO pipeline;

-- ── Verification ──────────────────────────────────────────────────────────────
-- SELECT table_name, sf_extraction_ts, oracle_start_scn, rows_copied, updated_at
-- FROM pipeline_watermarks
-- ORDER BY source_db, source_schema, table_name;
