apiVersion: v1
kind: Service
metadata:
  name: private-registry
  namespace: prod
  labels:
    app: private-registry
spec:
  type: NodePort
  selector:
    app: private-registry
  ports:
    - name: https
      port: 5000
      targetPort: 5000
      nodePort: 30500      # Accessible as <any-node-ip>:30500
      protocol: TCP
