# =============================================================================
# MongoDB — STAGING override values
# =============================================================================
global:
  defaultStorageClass: local-path

image:
  tag: "8.0"

architecture: standalone
auth:
  enabled: true
  existingSecret: mongodb-credentials
  existingSecretPasswordKey: mongodb-root-password

nodeSelector:
  kubernetes.io/hostname: master.local
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
persistence:
  enabled: true
  size: 5Gi
service:
  type: NodePort
  nodePorts:
    mongodb: "31017"
resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 500m
